// Facade for the mail service. The code lives in the mail-* modules below;
// callers and tests use require('./mail'), and t.mock.method(mail, name) on
// this object intercepts the calls that go through it (see mail-durable-jobs).
const { withMailAccountLock } = require('./mail-account-lock');
const hostPolicy = require('./mail-host-policy');
const folders = require('./mail-folders');
const durableJobs = require('./mail-durable-jobs');
const serverDelete = require('./mail-server-delete');
const syncControl = require('./mail-sync-control');
const { sendEmail } = require('./mail-send');

module.exports = {
  buildImapConnectionConfig: hostPolicy.buildImapConnectionConfig,
  withMailAccountLock,
  cancelMailAccountSync: syncControl.cancelMailAccountSync,
  stopMailAccountWork: syncControl.stopMailAccountWork,
  schedulePeriodicMailWork: syncControl.schedulePeriodicMailWork,
  MAIL_DISCOVERY_INTERVAL_SECONDS: syncControl.MAIL_DISCOVERY_INTERVAL_SECONDS,
  yieldMailReadWork: syncControl.yieldMailReadWork,
  runMailOperationsNow: syncControl.runMailOperationsNow,
  KNOWN_MAIL_HOST_SUFFIXES: hostPolicy.KNOWN_MAIL_HOST_SUFFIXES,
  DEFAULT_MAIL_SYNC_FETCH_LIMIT: syncControl.DEFAULT_MAIL_SYNC_FETCH_LIMIT,
  MAIL_SYNC_FETCH_LIMITS: syncControl.MAIL_SYNC_FETCH_LIMITS,
  MAIL_SERVER_DELETE_GRACE_MS: serverDelete.MAIL_SERVER_DELETE_GRACE_MS,
  MAIL_SERVER_DELETE_BATCH_SIZE: serverDelete.MAIL_SERVER_DELETE_BATCH_SIZE,
  MAIL_RAW_STORAGE_ROOT: serverDelete.MAIL_RAW_STORAGE_ROOT,
  MAIL_FOLDER_DEFINITIONS: folders.MAIL_FOLDER_DEFINITIONS,
  ALLOWED_MAIL_FOLDER_SET: folders.ALLOWED_MAIL_FOLDER_SET,
  SYSTEM_MAIL_FOLDER_SET: folders.SYSTEM_MAIL_FOLDER_SET,
  MAIL_SENDER_RULE_MATCH_TYPES: folders.MAIL_SENDER_RULE_MATCH_TYPES,
  normalizeMailFolderSlug: folders.normalizeMailFolderSlug,
  normalizeMailFolderDisplayName: folders.normalizeMailFolderDisplayName,
  allocateCollisionSafeMailFolderSlug: folders.allocateCollisionSafeMailFolderSlug,
  getSystemMailFolderDisplayName: folders.getSystemMailFolderDisplayName,
  loadMailFoldersForUser: folders.loadMailFoldersForUser,
  mailFolderExists: folders.mailFolderExists,
  normalizeHost: hostPolicy.normalizeHost,
  normalizeSyncFetchLimit: syncControl.normalizeSyncFetchLimit,
  normalizeMailAccountId: durableJobs.normalizeMailAccountId,
  isMailAccountSyncRunning: durableJobs.isMailAccountSyncRunning,
  isAnyMailAccountSyncRunning: durableJobs.isAnyMailAccountSyncRunning,
  getRunningMailSyncAccountIds: durableJobs.getRunningMailSyncAccountIds,
  isMailServerDeleteRunning: serverDelete.isMailServerDeleteRunning,
  isAnyMailServerDeleteRunning: serverDelete.isAnyMailServerDeleteRunning,
  getRunningMailServerDeleteAccountIds: serverDelete.getRunningMailServerDeleteAccountIds,
  normalizeSenderEmail: folders.normalizeSenderEmail,
  normalizeSenderDomain: folders.normalizeSenderDomain,
  normalizeMailSenderRuleInput: folders.normalizeMailSenderRuleInput,
  loadActiveMailSenderRules: folders.loadActiveMailSenderRules,
  pickBestMailSenderRuleMatch: folders.pickBestMailSenderRuleMatch,
  resolveMailSenderTargetFolder: folders.resolveMailSenderTargetFolder,
  createMailRoutingContext: folders.createMailRoutingContext,
  ensureDefaultMailFoldersForUser: folders.ensureDefaultMailFoldersForUser,
  isKnownMailProviderHost: hostPolicy.isKnownMailProviderHost,
  toBooleanFlag: hostPolicy.toBooleanFlag,
  isSelfSignedTlsError: hostPolicy.isSelfSignedTlsError,
  isTlsTrustError: hostPolicy.isTlsTrustError,
  assessMailHost: hostPolicy.assessMailHost,
  buildMailHostTrustResult: hostPolicy.buildMailHostTrustResult,
  validateMailHostPolicy: hostPolicy.validateMailHostPolicy,
  isAttachmentPathUnderUploads: serverDelete.isAttachmentPathUnderUploads,
  deleteStoredAttachmentFiles: serverDelete.deleteStoredAttachmentFiles,
  getMailRawStoragePath: serverDelete.getMailRawStoragePath,
  isMailRawPathUnderRoot: serverDelete.isMailRawPathUnderRoot,
  isUsableRawEmailArchive: serverDelete.isUsableRawEmailArchive,
  imapListToFolders: folders.imapListToFolders,
  listAvailableImapFolders: folders.listAvailableImapFolders,
  registerCustomImapFoldersForUser: folders.registerCustomImapFoldersForUser,
  pickImapSyncFolders: folders.pickImapSyncFolders,
  createImapBox: folders.createImapBox,
  ensureCustomImapFoldersForUser: folders.ensureCustomImapFoldersForUser,
  createRemoteMailFolderForUserAccounts: folders.createRemoteMailFolderForUserAccounts,
  getCurrentBoxUidValidity: serverDelete.getCurrentBoxUidValidity,
  loadExistingImportedUidSet: serverDelete.loadExistingImportedUidSet,
  recordMailServerMessageForDeletion: serverDelete.recordMailServerMessageForDeletion,
  seedMailServerDeletionQueueForAccount: serverDelete.seedMailServerDeletionQueueForAccount,
  markMailServerMessageDeleteStatus: serverDelete.markMailServerMessageDeleteStatus,
  deleteImapUid: serverDelete.deleteImapUid,
  processMailServerDeletionForAccount: serverDelete.processMailServerDeletionForAccount,
  runMailServerDeletionPass: serverDelete.runMailServerDeletionPass,
  testImapConnection: hostPolicy.testImapConnection,
  syncMailAccount: syncControl.syncMailAccount,
  startMailEngineScheduler: durableJobs.startMailEngineScheduler,
  runDurableMailJob: durableJobs.runDurableMailJob,
  runRecoveredReconcileJob: durableJobs.runRecoveredReconcileJob,
  scheduleMailAccountSync: syncControl.scheduleMailAccountSync,
  getMailSyncState: syncControl.getMailSyncState,
  sendEmail,
};
