module.exports = {
  ...require('./system'),
  ...require('./modules'),
  ...require('./notes'),
  ...require('./auth'),
  ...require('./contacts'),
  ...require('./settings'),
  ...require('./backup'),
  ...require('./search'),
  ...require('./recordings'),
  ...require('./calendar'),
  ...require('./mail'),
  ...require('./admin'),
  ...require('./games'),
  ...require('./notifications'),
  ...require('./offline'),
};
